#!/usr/bin/env python3
#Author: Basuh94

import os
dictionaryName = {
    "FIR":"PD2",
    "GRA":"PD3",
    "PLA":"PS",
    "POR":"PT",
    "PRO":"PY",
    "REV":"R",
    "SUM":"RS",
    "URD":"UD",
    "VIS":"VI",
    "WEA":"WL",
    "JUD":"JU",
    "LGI":"LE",
    "LEG":"LG",
    "LOR":"LRW",
    "M10":"10M",
    "M11":"11M",
    "M12":"12M",
    "M13":"13M",
    "M14":"14M",
    "M15":"15M",
    "MIR":"MI",
    "MER":"MM",
    "MRD":"MR",
    "NEM":"NE",
    "ODY":"OD",
    "ONS":"ON",
    "PSA":"P2",
    "PTK":"P3",
    "AVN":"DDH",
    "VVK":"DDI",
    "IVG":"DDJ",
    "SVT":"DDK",
    "HVM":"DDL",
    "JVV":"DDM",
    "SVC":"DDN",
    "EVK":"DDO",
    "ZVE":"DDP",
    "BVC":"DDQ",
    "NVO":"DDR",
    "MVM":"DDS",
    "MVG":"DDT",
    "EVI":"DDU",
    "DAR":"DK",
    "DEC":"DM",
    "DOP":"DPA",
    "FVD":"DRB",
    "DRS":"DS",
    "AND":"E01",
    "EOI":"E02",
    "EXO":"EX",
    "FDA":"FD",
    "FAL":"FE",
    "COL":"CS",
    "JVC":"DD2",
    "DDA":"DD3",
    "DVD":"DDC",
    "GVL":"DDD",
    "PVC":"DDE",
    "EVT":"DDF",
    "ATH":"AT",
    "BEA":"BD",
    "BEK":"BOK",
    "BRO":"BRB",
    "13C":"C13",
    "14C":"C14",
    "15C":"C15",
    "16C":"C16",
    "17C":"C17",
    "CHR":"CH",
    "CMA":"CM1",
    "CAN":"CMA",
    "FVO":"V16",
    "FVA":"V15",
    "ANH":"V14",
    "FVT":"V13",
    "FRE":"V12",
    "FVL":"V11",
    "FVR":"V10",
    "FVE":"V09",
    "URS":"US",
    "URL":"UL",
    "UNG":"UG",
    "ABU":"U",
    "ALP":"A",
    "BET":"B",
    "TOR":"TO",
    "TEM":"TE",
    "SAK":"SOK",
    "SHA":"SHM",
    "STR":"SH",
    "SCO":"SC",
    "REV":"RS",
    "STA":"ST",
    "S2K":"S00",
    "XTH":"10E",
    "4TH":"4E",
    "5TH":"5E",
    "6TH":"6E",
    "7TH":"7E",
    "8TH":"8E",
    "9TH":"9E",
    "ALL":"AL",
    "SOA":"ALA",
    "ARA":"AN",
    "APO":"AP",
    "ANT":"AQ",
    "ALR":"ARB",
    "ULM":"UMA",
    "UMA":"UBT",
    "ZEX":"EXP",
    "ODY":"OD",
    "BVC":"DDQ",
    "17W":"W17",
    "16W":"W16",
    "25M":"A25",
    "AKI":"MPS",
    "MMB":"MM2",
    "MMC":"MM3",
    "MYT":"MED"
}
directory = './'

def changeName(folderName, newName, directory):
    if(os.stat(directory)):
        try:
            os.rename(folderName, newName)
        except:
            print('La carpeta '+folderName+' no existe, no se ha podido renombrar por ' + newName )
    else:
        print ("Esta mierda no funciona")

for x, y in dictionaryName.items():
    changeName(x, y, directory)
    #print(directory + y)   
